CREATE TABLE author (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
  nick_name  VARCHAR(30),
  birth_date DATE         NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name  VARCHAR(255) NOT NULL,
  version    BIGINT       NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE book (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
  genre      VARCHAR(255),
  title      VARCHAR(50) NOT NULL,
  version    BIGINT      NOT NULL,
  library_id BIGINT,
  PRIMARY KEY (id)
);

CREATE TABLE book_author (
  book_id   BIGINT NOT NULL,
  author_id BIGINT NOT NULL,
  PRIMARY KEY (book_id, author_id)
);

CREATE TABLE book_review (
  id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
  content CLOB(255) NOT NULL,
  book_fk BIGINT    NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE library (
  id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(50) NOT NULL,
  PRIMARY KEY (id)
);

ALTER TABLE book
ADD CONSTRAINT FK_3pkewppfc8dyahqow87upbemb
FOREIGN KEY (library_id)
REFERENCES library;

ALTER TABLE book_author
ADD CONSTRAINT FK_6cmg2roopa9a4c97uxetgf2e9
FOREIGN KEY (author_id)
REFERENCES author;

ALTER TABLE book_author
ADD CONSTRAINT FK_q37qkj7serxg0bh56m450uigs
FOREIGN KEY (book_id)
REFERENCES book;

ALTER TABLE book_review
ADD CONSTRAINT FK_8vcgtv1iacqs96f7v4wafe4m8
FOREIGN KEY (book_fk)
REFERENCES book;
